classes:
- service.grafana.server.single
- service.postgresql.server.local
parameters:
  _param:
    postgresql_grafana_password: password
  grafana:
    server:
      enabled: true
  postgresql:
    server:
      database:
        grafana:
          encoding: UTF8
          locale: cs_CZ
          users:
          - name: grafana
            createdb: true
            password: ${_param:postgresql_grafana_password}
            host: 127.0.0.1
            rights: all privileges